name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests with test2json
      run: |
        mkdir -p test-results
        go test -v ./... | tee test-results/output.txt | go tool test2json > test-results/output.json
      continue-on-error: true

    - name: Show test results
      if: failure()
      run: cat test-results/output.txt

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results
