# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install dependencies
      run: go mod tidy

    - name: Build tests
      run: go test -c -o tests.test ./...

    - name: Run tests with test2json
      run: |
        mkdir -p test-results
        /usr/lib/go/bin/go tool test2json -t ./tests.test -test.v -test.paniconexit0 -test.run ^\QTestTranslateAndSimulate\E$ > test-results/output.json

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results
